spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    default: local
    active: local
  docker:
    compose:
      skip: true

#  flyway:
#    enable: false
#    url: jdbc:mysql://localhost:3306/soobook-database?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
#    user: root
#    password: verysecret

#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600 # 데이터 유지 시간(sec)
#      cache-null-values: true # null 캐싱 여부
#      host: localhost
#      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

springdoc:
  version: '@project.version@'
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none

jwt:
  token:
    clientSecret: BfqbCn6VnxW1UV1prH2qGvjq7hD9KzqpJExTFzmy77N6wp9wQtmUrT40CSawFFwnBW2q3dqrMi66eAgVKbxAyDEpqgxf2gGt59QL
    expireDuration: 1000s
    issuer: test