spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soobook-database?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate # flyway를 사용하므로 validate로 변경
    show-sql: true
  profiles:
    default: local
    active: local
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop

  flyway:
    enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-client-id
            client-secret: dummy-client-secret
            scope: profile,email

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

springdoc:
  version: '@project.version@'
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none

jwt:
  token:
    clientSecret: BfqbCn6VnxW1UV1prH2qGvjq7hD9KzqpJExTFzmy77N6wp9wQtmUrT40CSawFFwnBW2q3dqrMi66eAgVKbxAyDEpqgxf2gGt59QL
    expireDuration: 1000s
    issuer: test

kakao:
  api:
    key: dummy-key
