CREATE TABLE author (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '저자아이디',
  name VARCHAR(255) NOT NULL COMMENT '저자명',
  introduction VARCHAR(255) NOT NULL COMMENT '저자소개',
  created_at TIMESTAMP NOT NULL COMMENT '생성일시',
  modified_at TIMESTAMP NOT NULL COMMENT '수정일시'
) COMMENT '저자';